apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: blog
      hasuraService: custom
    name: blog
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: blog
      spec:
        containers:
        - image: ghost 
          env:
          - name: PRODUCTION
            value: "true"
          imagePullPolicy: IfNotPresent
          name: blog
          ports:
          - containerPort: 2368
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: blog
      hasuraService: custom
    name: blog
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 2368 
    selector:
      app: blog
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
